package:
  name: openocd-xpack
  version: 0.12.0_3

source:
  url: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-darwin-x64.tar.gz # [osx]
  sha256: 47931a1adde58ae6a7d99e4b0db5b9a62c568ce8e5232e958325d733f09e9995 # [osx]
  url: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-darwin-arm64.tar.gz # [arm64]
  sha256: 0084761ef77a5c3f2e098993f17cb4225819462b90c1378a1b35cea9cd466288 # [arm64]
  url: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-linux-x64.tar.gz # [linux64]
  sha256: 98c07aa34c6e02ac6ef0794494bc3bd9e2409d587723c5191ee4f0a4d179e39b # [linux64]
  url: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-linux-arm64.tar.gz # [aarch64]
  sha256: 892b2ecc624521e5947e4857d7dfd4af03e19ef37da73ae91215a1001864ed75 # [aarch64]
  url: https://github.com/xpack-dev-tools/openocd-xpack/releases/download/v0.12.0-3/xpack-openocd-0.12.0-3-win32-x64.zip # [win64]
  sha256: 94b51be5e5b38ac1c5814972eee9b062f0805bcd3ecc3bad5190fd659f6a3ab3 # [win64]

build:
  string: "0"
  binary_relocation: False
  
test:
  commands:
    - openocd --version

about:
  home: https://github.com/xpack-dev-tools/openocd-xpack
  license: MIT
  summary: xPack OpenOCD
  